export const TARGET_AGENT_COUNT = 150
export const TARGET_TRANSPORT_CAP = 150
export const MAX_ENEMIES_PER_AGENT = 3
export const MAX_EXHAUSTION_ALLOWED_ON_ASSIGNMENT = 30
export const MONEY_SAFETY_FLOOR_TURNS = 3
