export const EXPECTED_MISSIONS_COLUMN_WIDTH = 610
export const EXPECTED_LEADS_COLUMN_WIDTH = 620
export const EXPECTED_LEAD_INVESTIGATIONS_COLUMN_WIDTH = 660
export const EXPECTED_AGENTS_DEFAULT_VIEW_COLUMN_WIDTH = 640

export const CARD_WIDTH =
  78 +
  Math.max(
    EXPECTED_MISSIONS_COLUMN_WIDTH,
    EXPECTED_LEADS_COLUMN_WIDTH,
    EXPECTED_LEAD_INVESTIGATIONS_COLUMN_WIDTH,
    EXPECTED_AGENTS_DEFAULT_VIEW_COLUMN_WIDTH,
  )
