import {
  BATTLE_LOG_AGENT_COUNT_WIDTH,
  BATTLE_LOG_AGENT_HP_WIDTH,
  BATTLE_LOG_AGENT_SKILL_WIDTH,
  BATTLE_LOG_ENEMY_COUNT_WIDTH,
  BATTLE_LOG_ENEMY_HP_WIDTH,
  BATTLE_LOG_ENEMY_SKILL_WIDTH,
  BATTLE_LOG_ROUND_NUMBER_WIDTH,
  BATTLE_LOG_SKILL_RATIO_WIDTH,
  BATTLE_LOG_STATUS_WIDTH,
  COMBAT_LOG_AGENT_ID_WIDTH,
  COMBAT_LOG_ATTACKER_SKILL_WIDTH,
  COMBAT_LOG_ATTACKER_TYPE_WIDTH,
  COMBAT_LOG_ATTACK_ID_WIDTH,
  COMBAT_LOG_DAMAGE_WIDTH,
  COMBAT_LOG_DEFENDER_HP_WIDTH,
  COMBAT_LOG_DEFENDER_SKILL_WIDTH,
  COMBAT_LOG_ENEMY_ID_WIDTH,
  COMBAT_LOG_OUTCOME_WIDTH,
  COMBAT_LOG_ROLL_WIDTH,
  COMBAT_LOG_ROUND_NUMBER_WIDTH,
  COMBAT_LOG_THRESHOLD_WIDTH,
  MISSION_SITE_DETAILS_KEY_WIDTH,
  MISSION_SITE_DETAILS_VALUE_WIDTH,
} from './columnWidths'

const CHECKMARK_COLUMN_WIDTH = 50
const BORDER_WIDTH = 1
const PADDING_WIDTH = 8
const MUI_DATA_GRID_COLUMN_FILLER = 19
const DATA_GRID_BASE_WIDTH = 2 * BORDER_WIDTH + 2 * PADDING_WIDTH + MUI_DATA_GRID_COLUMN_FILLER
export const EXPECTED_MISSIONS_COLUMN_WIDTH = 710
export const EXPECTED_LEADS_COLUMN_WIDTH = 620
export const EXPECTED_LEAD_INVESTIGATIONS_COLUMN_WIDTH = 670
export const EXPECTED_AGENTS_DEFAULT_VIEW_COLUMN_WIDTH = 640
export const EXPECTED_AGENTS_TERMINATED_VIEW_COLUMN_WIDTH = 720
export const EXPECTED_ASSETS_COLUMN_WIDTH = 380
export const EXPECTED_CAPABILITIES_COLUMN_WIDTH = 440
export const EXPECTED_SITUATION_REPORT_COLUMN_WIDTH = 350

export const LEFT_COLUMN_CARD_WIDTH = 380

export const MIDDLE_COLUMN_CARD_WIDTH =
  DATA_GRID_BASE_WIDTH +
  Math.max(
    EXPECTED_MISSIONS_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_LEADS_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_LEAD_INVESTIGATIONS_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_AGENTS_DEFAULT_VIEW_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_AGENTS_TERMINATED_VIEW_COLUMN_WIDTH,
  )

export const RIGHT_COLUMN_CARD_WIDTH =
  DATA_GRID_BASE_WIDTH +
  Math.max(
    EXPECTED_ASSETS_COLUMN_WIDTH,
    EXPECTED_CAPABILITIES_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_SITUATION_REPORT_COLUMN_WIDTH,
  )

export const COMBAT_LOG_CARD_WIDTH =
  DATA_GRID_BASE_WIDTH +
  COMBAT_LOG_ATTACK_ID_WIDTH +
  COMBAT_LOG_ROUND_NUMBER_WIDTH +
  COMBAT_LOG_AGENT_ID_WIDTH +
  COMBAT_LOG_ENEMY_ID_WIDTH +
  COMBAT_LOG_ATTACKER_TYPE_WIDTH +
  COMBAT_LOG_OUTCOME_WIDTH +
  COMBAT_LOG_ATTACKER_SKILL_WIDTH +
  COMBAT_LOG_DEFENDER_SKILL_WIDTH +
  COMBAT_LOG_ROLL_WIDTH +
  COMBAT_LOG_THRESHOLD_WIDTH +
  COMBAT_LOG_DAMAGE_WIDTH +
  COMBAT_LOG_DEFENDER_HP_WIDTH // borders + padding + filler + columns

export const BATTLE_LOG_CARD_WIDTH =
  DATA_GRID_BASE_WIDTH +
  BATTLE_LOG_ROUND_NUMBER_WIDTH +
  BATTLE_LOG_STATUS_WIDTH +
  BATTLE_LOG_AGENT_COUNT_WIDTH +
  BATTLE_LOG_AGENT_SKILL_WIDTH +
  BATTLE_LOG_AGENT_HP_WIDTH +
  BATTLE_LOG_ENEMY_COUNT_WIDTH +
  BATTLE_LOG_ENEMY_SKILL_WIDTH +
  BATTLE_LOG_ENEMY_HP_WIDTH +
  BATTLE_LOG_SKILL_RATIO_WIDTH // borders + padding + filler + columns

export const MISSION_SITE_DETAILS_CARD_WIDTH =
  DATA_GRID_BASE_WIDTH + MISSION_SITE_DETAILS_KEY_WIDTH + MISSION_SITE_DETAILS_VALUE_WIDTH // borders + padding + filler + columns
