const CHECKMARK_COLUMN_WIDTH = 50
const BORDER_WIDTH = 1
const PADDING_WIDTH = 8
const MUI_DATA_GRID_COLUMN_FILLER = 19
export const EXPECTED_MISSIONS_COLUMN_WIDTH = 710
export const EXPECTED_LEADS_COLUMN_WIDTH = 620
export const EXPECTED_LEAD_INVESTIGATIONS_COLUMN_WIDTH = 670
export const EXPECTED_AGENTS_DEFAULT_VIEW_COLUMN_WIDTH = 640
export const EXPECTED_AGENTS_TERMINATED_VIEW_COLUMN_WIDTH = 720
export const EXPECTED_ASSETS_COLUMN_WIDTH = 380
export const EXPECTED_CAPABILITIES_COLUMN_WIDTH = 440
export const EXPECTED_SITUATION_REPORT_COLUMN_WIDTH = 350

export const LEFT_COLUMN_CARD_WIDTH = 380

export const MIDDLE_COLUMN_CARD_WIDTH =
  2 * BORDER_WIDTH +
  2 * PADDING_WIDTH +
  MUI_DATA_GRID_COLUMN_FILLER +
  Math.max(
    EXPECTED_MISSIONS_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_LEADS_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_LEAD_INVESTIGATIONS_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_AGENTS_DEFAULT_VIEW_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_AGENTS_TERMINATED_VIEW_COLUMN_WIDTH,
  )

export const RIGHT_COLUMN_CARD_WIDTH =
  2 * BORDER_WIDTH +
  2 * PADDING_WIDTH +
  MUI_DATA_GRID_COLUMN_FILLER +
  Math.max(
    EXPECTED_ASSETS_COLUMN_WIDTH,
    EXPECTED_CAPABILITIES_COLUMN_WIDTH + CHECKMARK_COLUMN_WIDTH,
    EXPECTED_SITUATION_REPORT_COLUMN_WIDTH,
  )
