export const AGENT_UPKEEP_COST = 5
export const AGENT_CONTRACTING_INCOME = AGENT_UPKEEP_COST * 3
export const AGENT_ESPIONAGE_INTEL = 5
export const AGENT_HIRE_COST = 50

export const AGENT_INITIAL_SKILL = 100
export const AGENT_INITIAL_EXHAUSTION = 0
export const AGENT_INITIAL_HIT_POINTS = 30

export const AGENT_EXHAUSTION_INCREASE_PER_TURN = 1
export const AGENT_EXHAUSTION_INCREASE_PER_ATTACK = 1
export const AGENT_EXHAUSTION_INCREASE_PER_DEFENSE = 1
export const AGENT_EXHAUSTION_RECOVERY_PER_TURN = 5

export const AGENT_RECOVERY_TURNS_FACTOR = 2

// 100, 130, 155, 175, 190, 205
export const MISSION_SURVIVAL_SKILL_REWARD = [30, 25, 20, 15]
export const AGENT_SUCCESSFUL_ATTACK_SKILL_REWARD = 4
export const AGENT_FAILED_ATTACK_SKILL_REWARD = 2
export const AGENT_SUCCESSFUL_DEFENSE_SKILL_REWARD = 2
export const AGENT_FAILED_DEFENSE_SKILL_REWARD = 1

export const SUPPRESSION_DECAY_PCT = 10

// Weapon damage ranges are +/- 50% of base damage
export const WEAPON_DAMAGE_RANGE_FACTOR = 0.5

// Agent weapon stats
export const AGENT_INITIAL_WEAPON_DAMAGE = 10

// Precision of 0.01%
export const CONTEST_ROLL_PRECISION = 10_000
