export const AGENT_UPKEEP_COST = 5
export const AGENT_CONTRACTING_INCOME = AGENT_UPKEEP_COST * 3
export const AGENT_ESPIONAGE_INTEL = 5
export const AGENT_HIRE_COST = 50
export const AGENT_INITIAL_SKILL = 100
export const AGENT_INITIAL_EXHAUSTION = 0
export const AGENT_INITIAL_HIT_POINTS = 30
export const AGENT_EXHAUSTION_INCREASE_PER_TURN = 1
export const AGENT_EXHAUSTION_RECOVERY_PER_TURN = 5
export const SUPPRESSION_DECAY_PCT = 10
// 100, 130, 155, 175, 190, 205
export const MISSION_SURVIVAL_SKILL_REWARD = [30, 25, 20, 15]
