# Deploys to
# https://konrad-jamrozik.github.io/game-ts/
# See docs/about_github_pages.md for more details.
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # Allow manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=24.3.0'

      - name: Install dependencies
        run: |
          npm clean-install

      - name: Run linter
        run: |
          npm run lint
        # 🚧KJA temporary linter ignore failures
        continue-on-error: true

      - name: Run formatter
        run: |
          npm run format

      - name: Run tests
        # --pool=forks adds test isolation. --retry=1 accommodates for flaky tests.
        run: |
          npm run test -- --pool=forks --retry=1

      - name: Build project
        run: |
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'web/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
